services:

  postgres:
    image: 'postgres:15.0'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=onek
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=pDB
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./data/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: